### ISSUE TITLE
Server Freezes for Duration of MaxIdleTimeout on Closing Multiple Unidirectional Streams

### ISSUE THREAD

**Issue by minchopm** [quic-go/webtransport-go#100]
Title:
Server Freezes for Duration of MaxIdleTimeout on Closing Multiple Unidirectional Streams

Issue Body:

Description:
I'm using a unidirectional stream where one client is the primary streamer (trough Ingest channel) and multiple clients receive messages from this stream (trough Delivery channel). When refreshing the browser for one of the clients, there's no noticeable impact on the system. However, when I close one more connection, the server seems to freeze for the duration specified in MaxIdleTimeout.

Steps to Reproduce:

Start a primary client streaming on a unidirectional stream.
Connect multiple clients to receive messages from this stream.
Refresh the browser for one of the clients - observe that there's no impact.
Close the connection for one of the clients.
Observe that the server freezes and remains unresponsive for the duration of MaxIdleTimeout.
Expected Behavior:
Closing or refreshing a client's connection should not cause the server to freeze or become unresponsive, regardless of the MaxIdleTimeout setting.

Actual Behavior:
The server becomes unresponsive and only restores after the MaxIdleTimeout duration when multiple client connections are closed. Additionally, it seems that during this MaxIdleTimeout, the server is attempting to stream data to the closed connection without success.

Environment:

Go version: [e.g., 1.17]
OS: [e.g., macOS Big Sur]
Any other relevant environment details.
Additional Context:
The stream is set up such that one client primarily streams data, and multiple clients receive these messages. It's essential for our use case that the server remains stable and responsive even when multiple clients disconnect.

**Comment by marten-seemann** [comment]
It's not clear to me that this is a webtransport-go issue, could be a browser issue as well (see https://github.com/quic-go/webtransport-go/issues/84, for example).

This would need to be reproduced using webtransport-go on the client and the server side. It might also be helpful to record a qlog on both the client and the server when the freezing happens.
