### ISSUE TITLE
can not create  lot of connection at the same time

### ISSUE THREAD

**Issue by someview** [quic-go/webtransport-go#104]
I have tried to test some basic performance of this package. The test code is in this repo [webtransport benchmark](https://github.com/someview/transport-benchmark).
when the client create conn about 100 -200 ，the quic client can not create connection. 
```
QuicConfig: &quic.Config{
				HandshakeIdleTimeout: time.Minute,
				MaxIdleTimeout:       time.Hour,
				MaxIncomingStreams:   1 << 20,
				Allow0RTT:            true,
			},

```
I have checkouted server config and client config，and adjust config params, but there is no effective. Is there some suggestion about this?[bench-server](https://github.com/someview/transport-benchmark/blob/dev/server/main.go)

**Comment by marten-seemann** [comment]
> the quic client can not create connection

What's the error?

**Comment by someview** [comment]
> > the quic client can not create connection
> 
> What's the error?

```
开始时间: 2023-11-01 09:46:07.182665388 +0000 UTC m=+0.001319361
时间: 2023-11-01 09:46:27.489569455 +0000 UTC m=+20.308223404 send: 390887 recv: 66861 rate: 22887
send err: 0
recv err: timeout: no recent network activity
2023/11/01 09:46:38 dial err: timeout: no recent network activity
exit status 1
```

**Comment by someview** [comment]
> > the quic client can not create connection
> 
> What's the error?

```
开始时间: 2023-11-01 09:49:55.50670567 +0000 UTC m=+0.001143886
2023/11/01 09:49:59 dial err: CONNECTION_REFUSED (remote)
exit status 1
```
This happens sometimes.

**Comment by someview** [comment]
> > > the quic client can not create connection
> > 
> > 
> > What's the error?
> 
> ```
> 开始时间: 2023-11-01 09:49:55.50670567 +0000 UTC m=+0.001143886
> 2023/11/01 09:49:59 dial err: CONNECTION_REFUSED (remote)
> exit status 1
> ```
> 
> This happens sometimes.

and server routines may be a problem：
```
server recv webtransport conn: 153 routines: 2156
server recv webtransport conn: 154 routines: 2166
server recv webtransport conn: 155 routines: 2168
server recv webtransport conn: 156 routines: 2170
server recv webtransport conn: 157 routines: 2172
server recv webtransport conn: 158 routines: 2219
```

**Comment by marten-seemann** [comment]
CONNECTION_REFUSED is expected, if the application can't process all the incoming connection requests at once. That's a feature, helping protect the server against a flood of requests.

**Comment by someview** [comment]
> CONNECTION_REFUSED is expected, if the application can't process all the incoming connection requests at once. That's a feature, helping protect the server against a flood of requests.

But the routine num seems not normal. If benchmark client was interrupted, there may be  over 10000 routines even there are only   200 quicconn and one conn has only one bidistream. May be somewhere routine leak
