### ISSUE TITLE
Error on server upgrade: "webtransport: request origin not allowed"

### ISSUE THREAD

**Issue by minchopm** [quic-go/webtransport-go#111]
### Issue Description
Attempting to connect via WebTransport from browser to the server results in a failure with the error message "webtransport: request origin not allowed". This issue occurs when handling requests on the server.

### Error Message
webtransport: request origin not allowed

### Steps to Reproduce
1. Configure the server with HTTP/3 support and TLS.
2. Handle incoming requests and attempt to upgrade to a WebTransport session.
3. The upgrade fails and logs the above error message.

### Expected Behavior
The server should successfully upgrade to a WebTransport session without any errors.

### Actual Behavior
The server upgrade process fails, and the error "webtransport: request origin not allowed" is logged.

### Environment
- Go version: 1.20 and 1.18
- OS: Mac M1 Max

### Code Snippet
```
func main() {
	server := webtransport.Server{
		H3: http3.Server{
			Addr:       ":8444",
			QuicConfig: &quic.Config{Allow0RTT: true},
			TLSConfig:  &tls.Config{InsecureSkipVerify: true},
		},
	}

	log.SetFormatter(&log.TextFormatter{})

	http.HandleFunc("/moqingest/", func(rw http.ResponseWriter, r *http.Request) {
		session, err := server.Upgrade(rw, r)
		if err != nil {
			log.Printf("upgrading failed: %s", err)
			rw.WriteHeader(500)
			return
		}

		ingestSessionID := "I-" + uuid.New().String() + "-" + r.URL.Path

		log.Info(fmt.Sprintf("%s - Accepted incoming WebTransport session. rawQuery: %s", ingestSessionID, r.URL.RawQuery))

		handleWebTransportIngestStreams(session, ingestSessionID)
	})

	http.HandleFunc("/moqdelivery/", func(rw http.ResponseWriter, r *http.Request) {
		session, err := server.Upgrade(rw, r)
		if err != nil {
			log.Printf("upgrading failed: %s", err)
			rw.WriteHeader(500)
			return
		}

		deliverySessionID := "D-" + uuid.New().String() + "-" + r.URL.Path

		log.Info(fmt.Sprintf("%s - Accepted incoming WebTransport session. rawQuery: %s", deliverySessionID, r.URL.RawQuery))
		handleWebTransportDeliveryStreams(session, deliverySessionID)
	})

	if err := server.ListenAndServeTLS("../certs/certificate.pem", "../certs/certificate.key"); err != nil {
		log.Fatalln("listen err:", err)
	}
}
```

**Comment by marten-seemann** [comment]
See https://github.com/quic-go/webtransport-go/blob/14f48ac857960dd90261b7b66a468153acc86275/server.go#L40-L44
