### ISSUE TITLE
Update quic-go to v0.48.2 plz

### ISSUE THREAD

**Issue by zishang520** [quic-go/webtransport-go#164]
Version 0.8.0 does not support security fix updates of v0.48.0 and above, and a new version needs to be released

**Comment by marten-seemann** [comment]
I guess you haven't read the README, have you?

**Comment by zishang520** [comment]
Heartbreak.... But thank you very much.

**Comment by marten-seemann** [comment]
You can just bump the quic-go version in your project's `go.mod`. It's a patch release, hence there are no breaking changes.

**Comment by zishang520** [comment]
Incompatible with newer versions due to structural changes: https://github.com/quic-go/webtransport-go/commit/4ac2c9250e66042470c55c7e9f431269c7dbd3ed

**Comment by marten-seemann** [comment]
That's not correct, but this is not a support forum.
