### ISSUE TITLE
quic-go: HasPacingBudget Issue

### ISSUE THREAD

**Issue by moksh-samespace** [quic-go/webtransport-go#69]
Facing this issue with quic-go. Where my binary crashes on low network connectivity
 
 github.com/quic-go/quic-go/internal/congestion.(*cubicSender).HasPacingBudget

**Comment by marten-seemann** [comment]
What do you mean by crashing?

**Comment by moksh-samespace** [comment]
So I am using the quic-go and c-go to build a native desktop app. On low connectivity or network switch, I get a crash report from the mac console stating the above error.

**Comment by marten-seemann** [comment]
You didn’t provide any error.
