### ISSUE TITLE
How to negotiate a subprotocol ? 

### ISSUE THREAD

**Issue by om26er** [quic-go/webtransport-go#70]
WebTransport is raw as it provides an ordered stream of bytes. To make it useful for my case I need to negotiate a subprotocol, so that my client and server know what serializer to use to "parse" the length-prefixed messaging that I am going to do.

Would it make sense to use a `Sec-WebTransport-Protocol` header before calling `Upgrade` ?  i.e. something like
```
w.Header().Add("Sec-WebTransport-Protocol", "wamp.2.cbor")
```

Or is there a more elegant way ?

**Comment by marten-seemann** [comment]
> To make it useful for my case I need to negotiate a subprotocol

Would that be per session or per stream?



> Would it make sense to use a `Sec-WebTransport-Protocol` header before calling `Upgrade` ? i.e. something like
> 
> ```
> w.Header().Add("Sec-WebTransport-Protocol", "wamp.2.cbor")
> ```
> 
> Or is there a more elegant way ?

Using a header would be one way to do it. Alternatively, you could use a different URL (or a GET parameter).

**Comment by om26er** [comment]
Since I am looking at multiplexing multiple WAMP sessions on a single stream, it would make more sense if the protocol negotiation was per stream.

In my case the URL is going to always stay the same like `https://localhost:12345/webtransport`

**Comment by marten-seemann** [comment]
You don't have HTTP semantics when opening new streams, only when opening a new session.

**Comment by om26er** [comment]
thanks, I am currently making use of headers to negotiate the subprotocol. For my usecase all subsequent streams are supposed to use the same protocol anyways
