### ISSUE TITLE
Corruption of unknown origin in data sent through unidirectional stream

### ISSUE THREAD

**Issue by Tiger-I-Yang** [quic-go/webtransport-go#76]
I unfortunately don't know much about this issue but I have thoroughly documented the events and my setup here: https://stackoverflow.com/questions/76177807/corruption-of-unknown-origin-in-audio-libopus-and-video-nvenc-hevc-bitstream/76190994?noredirect=1#comment134363768_76190994

Specifically, I sent pure hevc and opus bitstreams through unidirectional streams, but they're getting corrupted some way as depicted in the video (https://youtu.be/wAY5w4zlku4). I know the issue is at the web transport stream since I switched to using datagrams and the corruption is gone.

**Comment by marten-seemann** [comment]
We have a bunch of tests both here and in quic-go that assert that stream data is not corrupted, so I'd be very surprised if that's the problem.

Do you have a simpler reproducer than your current setup?

**Comment by Tiger-I-Yang** [comment]
I tried using the unidirectional streams again for the video bitstream only

for the server code, all I effectively did was replace:

activeSession.SendMessage(buffer[0:len])

with this: (I verified that actualLen always == len)

actualLen, _ := videoStream.Write(buffer[0:len])

that was enough for the corruption to come back. I am using go 1.18.10 on windows 11, and I'm using the webtransport browser API for the client. Assuming there is nothing wrong on the go side, the most likely culprit would be the browser API, which is stated to be experimental

**Comment by marten-seemann** [comment]
Not sure what to do here. This doesn’t seem to be an issue on our side.
