### ISSUE TITLE
WebTransport Datagrams

### ISSUE THREAD

**Issue by oott123** [quic-go/webtransport-go#8]
There are "datagrams" in webtransport: 

https://github.com/w3c/webtransport/blob/main/explainer.md#example-of-sending-unreliable-game-state-to-server-using-datagrams

But I can't find implementation of this in webtransport-go. Is it a feature that haven't implemented, or I have missed something?

Thanks!

**Comment by marten-seemann** [comment]
Datagram support is not yet implemented.

**Comment by tchakabam** [comment]
@marten-seemann Is adding support on any roadmap yet? And would you potentially want to accept PRs on this topic?

**Comment by marten-seemann** [comment]
Blocked on https://github.com/quic-go/quic-go/issues/3522.
