### ISSUE TITLE
Large or Many Writes on a Stream get blocked

### ISSUE THREAD

**Issue by ansemjo** [quic-go/webtransport-go#84]
I am facing an issue where, when I am sending too much data at once over a `BidirectionalStream`, it gets blocked on `.Write()` and this part of the application just hangs. Other `UnidirectionalStream`s, which send much smaller packets, still work simultaneously even when the first stream is "blocked".

(**Update:** this may be a Firefox issue, since I cannot reproduce this with a Go client or Chromium ...)

For lack of a better method – stepping through the application with VSCode produces lots of "timed out" and "stream closed" errors – I tried inserting some `fmt.Println()` messages and I *think* I can pinpoint it to the [`<-s.writeChan` line](https://github.com/quic-go/quic-go/blob/0fe21c7d6fc29a1f493a751ea524c3c9428f9848/send_stream.go#L169) in `quic-go/send_stream.go`. (Maybe this issue would be better suited in that repository but I am experiencing this issue in the context of WebTransport in the Browser, so I am first reporting it here.)

This happens either with a single large (~ 32 MB) write or multiple smaller (~ 100 KB) writes in short succession. If I insert a `10 ms` delay between those smaller packets, everything runs smoothly. But that can't be the correct way to go about this ...

---

I tried to write a minimal reproducer here: https://gist.github.com/ansemjo/72e1fc95a8c6e19cabfa750e45eae185

Running the WebTransport server with Go `go1.20.5 linux/amd64` and opening the page in Firefox `115.0.1 (64-bit)`, I get:

```
$ go run main.go
2023/07/11 16:38:05 WebTransport listening on https://localhost:7443/transport (UDP)
2023/07/11 16:38:05 static files listening on https://localhost:7443/
2023/07/11 16:38:07 connection from 127.0.0.1:45628
2023/07/11 16:38:07 write blob #00
2023/07/11 16:38:07 write blob #01
2023/07/11 16:38:07 write blob #02
2023/07/11 16:38:07 write blob #03
2023/07/11 16:38:07 write blob #04
2023/07/11 16:38:07 write blob #05
2023/07/11 16:38:07 write blob #06
2023/07/11 16:38:07 write blob #07
2023/07/11 16:38:07 write blob #08
2023/07/11 16:38:07 write blob #09
2023/07/11 16:38:07 write blob #10
2023/07/11 16:38:07 write blob #11
2023/07/11 16:38:07 write blob #12
2023/07/11 16:38:07 write blob #13
2023/07/11 16:38:07 write blob #14
2023/07/11 16:38:07 write blob #15
2023/07/11 16:38:07 write blob #16
2023/07/11 16:38:07 write blob #17
```

![image](https://github.com/quic-go/webtransport-go/assets/11139925/35b163fd-2dbe-49a1-a768-8affc190cce0)

Notably, the server never reaches the `log.Println("done sending.")` line and Firefox always receives data in 64 KiB chunks ... If I uncomment the `time.Sleep(10 * time.Millisecond)` in the loop, everything is sent correctly. In my application, the stream is passed on to a Worker and sending blocks even earlier.

Is this a race condition? Is there a way to "flush the buffer" or anything like that?

---

**UPDATE:** unfortunately (or luckily, however you look at it ..) I can neither reproduce this with [a Go client](https://gist.github.com/ansemjo/72e1fc95a8c6e19cabfa750e45eae185#file-client-go), nor Chromium ...

**Comment by marten-seemann** [comment]
Sounds like a Firefox issue then? Have you recorded a qlog and loaded it into [qvis](https://qvis.quictools.info/#/files) yet? That would allow you to see why exactly things are getting stuck.

**Comment by ansemjo** [comment]
Well, this is fun ..
I am trying to capture a qlog by setting `network.http.http3.enable_qlog` in `about:config` .. and this *generally* works. Visiting Google produces a useful trace, too. But my application on `localhost` only seems to record the handshake for some reason. When I try to host the application on a Hetzner server, the issue does not appear at all; probably because the round-trip times are long enough to avoid whatever is going wrong here. I'll give it a few more attempts.

**Comment by ansemjo** [comment]
I somehow managed to grab a successful qlog of a connection where this issue occured. In the visualization it looked like all data has been received successfully by Firefox this time (the "Packetization" tab showed the expected number of "Bytes received"). Yet the async iterator in Firefox was still stuck after about 1.2 MiB.

Two days ago I thought that maybe *increasing* the receive buffer size would help. **But it turns out that *decreasing* it actually solved my issue.**

The setting `network.http.http3.recvBufferSize` is set to `1048576` by default for me. I reduced this to `32768` (32 KiB) and all data was transmitted correctly. When `network.http.http3.enable_qlog` is also enabled, I can increase the receive buffer size further to `65536` (64 KiB). So it seems that I just need to "slow down" reception of frames somehow.

Anyway. This really *seems* like a Firefox issue to me, so I'm closing this issue. I have no idea how to debug this further but I'm happy to have found a way around it for now.

**Comment by marten-seemann** [comment]
You could also try recording a qlog from the quic-go side. Might be interesting to get the server's perspective on this.

**Comment by ansemjo** [comment]
Sure. I've added a connection tracer to the reproducer [per the example in `quic-go`](https://github.com/quic-go/quic-go/blob/master/example/client/main.go) and recorded a connection where this issue occured from "both sides". For this I reset the receive buffer size in Firefox to its default value.

* [quic_server.qlog.txt](https://github.com/quic-go/webtransport-go/files/12050231/quic_server.qlog.txt)
* [quic_client.qlog.txt](https://github.com/quic-go/webtransport-go/files/12050234/quic_client.qlog.txt)

You can see that the server hangs after 19 iterations (~ 1945600 bytes):

![Screenshot from 2023-07-14 14-05-14](https://github.com/quic-go/webtransport-go/assets/11139925/91d14bed-bdbc-4734-ac23-6cda3e695ff7)

And the browser only "received" 889941 bytes. (The `CHUNK`s don't map cleanly to iterations because I am just sending zeroes and log the chunks as fast as they arrive in the async iterator.)

![Screenshot from 2023-07-14 14-04-50](https://github.com/quic-go/webtransport-go/assets/11139925/d3a7d246-37ad-44b8-b3e9-e8dd0f39764a)

I haven't looked at the qvis of those two logs in detail yet but maybe you can find something interesting in them. Luckily, the client log is not corrupted this time; it apprears this also only happens sporadically.
